### ISSUE TITLE
add get method for precinct name string for screen presentatio

### ISSUE THREAD

**Issue by cwulfman** [cwulfman/voterartifacts#2]

**Comment by cwulfman** [comment]
It's already defined:

```
╰─$ node
Welcome to Node.js v12.16.1.
Type ".help" for more information.
> const VoterArtifacts = require('./src/voterartifacts')
undefined
> let foo = new VoterArtifacts('A')
undefined
> foo.precinct
'precinct_1'
```

**Comment by trustthevote** [comment]
I can see that you can use the dot operation find the precinct field that is the file path extension to get the requisite folder for the precinct. That's not really the precinct, but rather a precinct ID for purpose limited to the file tree. What's need for the UI is a get method for the name of the precinct e.g. "Precinct 1" or even better "Precinct 1 Downtown" (the precincts had names as well as I recall. The fact the directory name is similar, doesn't mean that the dir name is usable in the UI.

I wouldn't be pernickety about this normally, but there seems to be a high degree of scrutiny of the MVP code, and fine grain fit and finish seems more important than usual. Esp. since we committed today to this app being used for end user usability and accessibility testing as well
